# Generated by Django 5.1.7 on 2025-04-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrule',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='borrowingrule',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
