# Generated by Django 5.2 on 2025-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuplateau',
            name='game_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
