# Generated by Django 5.1.7 on 2025-04-10 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth import get_user_model

def set_default_user(apps, schema_editor):
    Borrow = apps.get_model('personnel', 'Borrow')
    User = get_user_model()  # Utilisation de la méthode get_user_model() pour récupérer le modèle User
    try:
        default_user = User.objects.get(id=1)  # Essayez de récupérer l'utilisateur avec l'ID 1
    except User.DoesNotExist:
        # Si l'utilisateur avec l'ID 1 n'existe pas, vous pouvez définir un autre utilisateur par défaut
        default_user = User.objects.first()  # Prendre le premier utilisateur existant (ou créez-en un)

    # Mettre à jour les lignes avec un utilisateur par défaut si nécessaire
    Borrow.objects.filter(user__isnull=True).update(user=default_user)


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_borrowingrule_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, default=1),
        ),
        migrations.RunPython(set_default_user),  # Applique la fonction pour définir l'utilisateur par défaut
    ]
