# Generated by Django 5.1.7 on 2025-04-07 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_member_address_member_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
