# Generated by Django 5.2 on 2025-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeuplateau',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jeuplateau',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jeuplateau',
            name='creators',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jeuplateau',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
