# Generated by Django 5.2 on 2025-04-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_jeuplateau_available_jeuplateau_is_visible'),
        ('personnel', '0004_jeuplateau_available_jeuplateau_is_visible_and_more'),
    ]

    operations = [
    ]
