# Generated by Django 5.2 on 2025-04-28 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('dvd', 'DVD'), ('cd', 'CD'), ('board_game', 'Board Game')], max_length=50)),
                ('can_borrow', models.BooleanField(default=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediatheque_media_set', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('creators', models.CharField(max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('game_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('author', models.CharField(max_length=200)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('artist', models.CharField(max_length=200)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mediatheque.media')),
                ('producer', models.CharField(max_length=200)),
            ],
            bases=('mediatheque.media',),
        ),
        migrations.CreateModel(
            name='MediathequeBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('is_late', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediatheque.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediatheque_borrow_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_returned'], name='mediatheque_user_id_f1380b_idx')],
            },
        ),
    ]
